name: bad-project
on:
  push:
    branches:
      - "*"
  workflow_dispatch:

env:
  POSTGRES_DB: sign_lang_test
  POSTGRES_USERNAME: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST: postgres

jobs:
  testing:
    runs-on: ubuntu-latest
    container: node:18
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{env.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{env.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - run: |
          yarn install
          yarn knex migrate:latest --env test
          yarn knex seed:run --env test
          yarn test
  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: ssh to pull latest version and restart
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd BAD-Project-Sign-Language
            git pull origin main
            yarn install
            yarn knex migrate:latest --env production
            pm2 restart bad-project
          host: sign-language-monster.live
          username: ubuntu
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
